//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace _3000_Dictionary_List
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/ChineseStudyDataSet1.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/ChineseStudyDataSet1.xsd", IsNullable = false)]
    public partial class ChineseStudyDataSet
    {

        private ChineseStudyDataSetItem3000Characters[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("3000-Characters")]
        public ChineseStudyDataSetItem3000Characters[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/ChineseStudyDataSet1.xsd")]
    public partial class ChineseStudyDataSetItem3000Characters
    {

        private string idField;

        private string fEseqField;

        private string zhuyinField;

        private string traditionalField;

        private string englishField;

        private string numPinyinField;

        private string critPinyinField;

        private string simplifiedField;

        private string cjiField;

        /// <remarks/>
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string FEseq
        {
            get
            {
                return this.fEseqField;
            }
            set
            {
                this.fEseqField = value;
            }
        }

        /// <remarks/>
        public string Zhuyin
        {
            get
            {
                return this.zhuyinField;
            }
            set
            {
                this.zhuyinField = value;
            }
        }

        /// <remarks/>
        public string Traditional
        {
            get
            {
                return this.traditionalField;
            }
            set
            {
                this.traditionalField = value;
            }
        }

        /// <remarks/>
        public string English
        {
            get
            {
                return this.englishField;
            }
            set
            {
                this.englishField = value;
            }
        }

        /// <remarks/>
        public string NumPinyin
        {
            get
            {
                return this.numPinyinField;
            }
            set
            {
                this.numPinyinField = value;
            }
        }

        /// <remarks/>
        public string CritPinyin
        {
            get
            {
                return this.critPinyinField;
            }
            set
            {
                this.critPinyinField = value;
            }
        }

        /// <remarks/>
        public string Simplified
        {
            get
            {
                return this.simplifiedField;
            }
            set
            {
                this.simplifiedField = value;
            }
        }

        /// <remarks/>
        public string Cji
        {
            get
            {
                return this.cjiField;
            }
            set
            {
                this.cjiField = value;
            }
        }
    }
}
